[package]
name = "kube-health-check-actix"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Actix-Web adapter for kube-health-check"
readme = "../README.md"
keywords = ["kubernetes", "health", "actix", "readiness", "liveness"]
categories = ["network-programming", "asynchronous", "web-programming"]

[dependencies]
kube-health-check = { workspace = true }
actix-web = { workspace = true }
serde_json = { workspace = true }
