[package]
name = "kube-health-check-rocket"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Rocket adapter for kube-health-check"
readme = "../README.md"
keywords = ["kubernetes", "health", "rocket", "readiness", "liveness"]
categories = ["network-programming", "asynchronous", "web-programming"]

[dependencies]
kube-health-check = { workspace = true }
rocket = { workspace = true }
