[package]
name = "kube-health-check-hyper"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Hyper adapter for kube-health-check"
readme = "../README.md"
keywords = ["kubernetes", "health", "hyper", "readiness", "liveness"]
categories = ["network-programming", "asynchronous", "web-programming"]

[dependencies]
kube-health-check = { workspace = true }
hyper = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
serde_json = { workspace = true }
