[package]
name = "kube-health-check-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
kube-health-check = { path = ".." }

[[bin]]
name = "fuzz_sanitize_error"
path = "fuzz_targets/fuzz_sanitize_error.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
